spring:
    application:
        name: notification
    profiles:
        group:
            local: domain
            dev: domain
    jpa:
        hibernate:
            ddl-auto: create
logging:
    level:
        co.kr.woojjam.infrastructure: debug
        org.hibernate.SQL: debug
        org.hibernate.orm.jdbc.bind: trace
---
spring:
    config:
        activate:
            on-profile: local
---
spring:
    config:
        activate:
            on-profile: dev
