spring:
  application:
    name: aop
  profiles:
    active: local
    group:
      local: domain
      dev: domain
logging:
  level:
    co.kr.woojjam.aop: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
