spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

logging:
  level:
#    com.woojjam.schedule: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
