spring:
  application:
    name: notification
  profiles:
    group:
      local: domain
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    co.kr.woojjam.kakao: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
