spring:
  application:
    name: aop
  profiles:
    active: local
    group:
      local: domain
      dev: domain
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

#logging:
#  level:
#    co.kr.woojjam.aop: debug
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace
---
spring:
  config:
    activate:
      on-profile: local

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace

---
spring:
  config:
    activate:
      on-profile: dev
