name: deploy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

  pull_request:
    branches:
      - "develop"
      - "study/*"

permissions: write-all

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Set up JDK 17

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run Tests with JaCoCo
        run: ./gradlew testCodeCoverageReport

        # 테스트커버리Report를 PR에 Comment에 등록합니다. (Instruction 기준)
      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/jacoco-test-reports/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 10
          min-coverage-changed-files: 75
          title: "⭐️Code Coverage"
          update-comment: true
