name: deploy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

  pull_request:
    branches:
      - "develop"
      - "study/*"

permissions: write-all

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Set up JDK 17

    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle
      run: ./gradlew clean build
      shell: bash

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Run Tests with JaCoCo
      run: ./gradlew clean build

    - name: Upload JaCoCo Report
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: build/reports/index.xml

    - name: Report coverage to PR
      uses: dorny/test-reporter@v1
      with:
        name: Jacoco Test Coverage
        path: build/reports/index.xml
        reporter: jacoco
        fail-on-error: false
